jobs:
  build:
    runs-on: ubuntu-latest
    needs: test  # Remove 'needs: test' if no tests are being run
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-docker-image:${{ github.sha }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push my-docker-image:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # You can still keep this to deploy after building
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/backend
            docker pull my-docker-image:${{ github.sha }}
            docker stop $(docker ps -q --filter ancestor=my-docker-image)
            docker run -d -p 80:80 my-docker-image:${{ github.sha }}