name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # This will trigger the workflow when code is pushed to master
  pull_request:
    branches:
      - master  # This will trigger the workflow when a PR is made to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run tests (replace this step if you don’t have tests)
      - name: Run tests
        run: |
          pytest  # Replace with your actual test command if needed

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-backend .

      # Push Docker image to DockerHub (if applicable)
      - name: Push Docker image to DockerHub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push my-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will run after the build job is complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # SSH into EC2 and deploy
      - name: Deploy to EC2
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem ubuntu@$EC2_PUBLIC_IP "docker pull my-backend && docker run -d -p 8000:8000 my-backend"
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}