name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python (if you have Python tests)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the version you need for your tests

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if necessary

      - name: Run tests
        run: |
          pytest  # Replace with the actual command to run your tests

  # Job to build Docker image
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-app:$GITHUB_SHA .  # Replace with your app name

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-app:$GITHUB_SHA ${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA

  # Job to deploy on EC2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA
          EOF