name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug - Show Docker Username
        run: echo "DOCKER_USERNAME=$DOCKER_USERNAME"

      - name: Build Docker image
        run: |
          echo "Building Docker image for $DOCKER_USERNAME"
          docker build -t "${DOCKER_USERNAME}/blockhouse-web:latest" .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Login to DockerHub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push "${DOCKER_USERNAME}/blockhouse-web:latest"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem ubuntu@$EC2_PUBLIC_IP "docker pull ${DOCKER_USERNAME}/blockhouse-web:latest && docker run -d -p 8000:8000 ${DOCKER_USERNAME}/blockhouse-web:latest"
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}